version: "3"

services:
  atlas:
    container_name: HERMES_SERVER
    build: "."
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - "8082:8082"
    networks:
      - api_custom_net

networks:
  api_custom_net:
    external: true
