version: "3"

services:
  hermes:
    container_name: HERMES_SERVER
    build: "."
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - "8083:8083"
    networks:
      - api_custom_net

networks:
  api_custom_net:
    external: true
