version: "3"

services:
  atlas:
    container_name: ALTAS_SERVER
    build: "."
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - "8082:8082"
    depends_on:
      - db
    links:
      - db
    networks:
      - api_custom_net

  db:
    image: "mongo"
    container_name: MONGODB
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - api_custom_net

networks:
  api_custom_net:
    external: true
