version: "3"

services:
  api:
    container_name: API_SERVER
    build: "."
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - "3333:3333"
    networks:
      - custom_net

  db:
    image: "mongo"
    container_name: MONGODB
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - custom_net

networks:
  custom_net:
    driver: bridge
